spring.application.name=movies
spring.datasource.url= jdbc:mysql://localhost:3306/Movies
spring.datasource.username=root
spring.datasource.password=densil@raja

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=densil.raja@gmail.com
spring.mail.password=tzkv trvn zyfp xsjf

spring.mail.properties.mail.smtp.auth=truth
spring.mail.properties.mail.smtp.starttls.enable=true